name: Manual Deploy to Cloud

on:
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render backend deploy
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
        # Set RENDER_BACKEND_DEPLOY_HOOK in your GitHub repo secrets

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render frontend deploy
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK }}
        # Set RENDER_FRONTEND_DEPLOY_HOOK in your GitHub repo secrets
